// src/app/layout.tsx
import type { Metadata } from "next";
// Geist フォントのインポートを削除またはコメントアウト
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// フォントの定義を削除またはコメントアウト
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // html langを日本語に設定
    <html lang="ja">
      {/* classNameからフォント変数を削除 */}
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
